### ISSUE TITLE
Authentication Not work with  sabredav aka. sabre/dav Sabre -- 401

### ISSUE THREAD

**Issue by equwal** [miquels/davfs3#20]
https://sabre.io/dav/authentication/

I just used the default options. I can tell the client is extra suspictious because the behaviour of this client is different when I send the pass option as a mount option or as environment variables.

When I use environment variables, for some reason this thing tries to use the `http_proxy` value also. And I get different error codes.

```
$> http_proxy="" https_proxy="" WEBDAV_USERNAME=broken WEBDAV_PASSWORD='yEAwvY0ZH6ymUYrtbdbswtkLH' mount -t webdavfs "https://us0.co/sabredav/server.php" .mnt
mount.webdavfs: 401 Unauthorized
$> sudo mount -t webdavfs -ousername=broken,password=yEAwvY0ZH6ymUYrtbdbswtkLH,allow_other  "https://us0.co/sabredav/server.php" ~/.mnt
mount.webdavfs: 401 Unauthorized
```
I was able to connect with cadaver though. That's a real username/password pair, feel free to mess around with my service.

**Comment by miquels** [comment]
Here's your problem:

```
$ curl -i -X OPTIONS --basic --user 'broken:yEAwvY0ZH6ymUYrtbdbswtkLH' https://us0.co/sabredav/server.php
HTTP/1.1 401 Unauthorized
Server: nginx/1.22.1
Date: Tue, 01 Aug 2023 15:27:07 GMT
Content-Type: application/xml; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
WWW-Authenticate: Digest realm="SabreDAV",qop="auth",nonce="64c9244b6ed88",opaque="df58bdff8cf60599c939187d0b5c54de"

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.2.2</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured</s:message>
</d:error>
```

webdavfs only supports `basic` authentication, `digest` is not implemented. configure your sabredav server to also accept basic auth.

**Comment by equwal** [comment]
Thank you

**Comment by equwal** [comment]
Works with a mongrel nginx using the apache-utils password thing
```
auth_basic "Live Coding";
auth_basic_user_file /etc/apache2/.htpasswd;
```
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
