### ISSUE TITLE
permission denied can't write to the fuse

### ISSUE THREAD

**Issue by equwal** [miquels/davfs3#23]
test case:
```
echo 'x' > mnt/x
echo: write error: permission denied
sudo sh -c "echo 'x' >mnt/x"
sh: 1: echo: echo: I/O error
```
I tried mounting with different options to fudge the permissions but nothing changes here.

**Comment by miquels** [comment]
Your webdav server must support partial writes for this to work. That means using Apache's `mod_dav`, using a `SabreDav` based server with [partial-updates](https://sabre.io/dav/http-patch/) enabled, or [webdav-server-rs](https://github.com/miquels/webdav-server-rs).

**Comment by equwal** [comment]
You can see my server in the other issue, it has the http patch plugin added

**Comment by equwal** [comment]
https://github.com/miquels/webdavfs/issues/21

**Comment by equwal** [comment]
It looks like my friends are managing to use my server with VSCode extensions that seem to support HTTP Partial updates. I think this is a bug in webdavfs.

**Comment by equwal** [comment]
actually, I think my server is bugged
